console.log("School Name = MG Inter College");
console.log("Class = Xth");
console.log("Student Name = Pawan Kumar Gupta");
console.log("Father Name  = K.M. Gupta");
console.log("D.O.B = 22/06/1998");
console.log();
console.log("Subject  Total Marks  Obtained Marks  Pass/Fail");
console.log("Hindi      100             90           Pass");
console.log("Science    100             90           Pass");
console.log("Maths      100             90           Pass");
console.log("English    100             90           Pass");
console.log("Computer   100             90           Pass");
console.log();
console.log("Total Marks = 500");
console.log("Marks Obtained = 450");
console.log("Percentage = 90%");
console.log("Grade = Ist Division (Honours)");
console.log("Final Result = Pass");